Pharmidex.Admin/Controllers/StudiesController.cs
using AmarnaEnergy.IServices;
using Microsoft.AspNet.Identity;
using Pharmidex.Core.Enums;
using Pharmidex.Core.Helpers;
using Pharmidex.Core.Models;
using Pharmidex.Core.Models.Base;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Pharmidex.Admin.Controllers
{
    public class StudiesController : ApplicationBaseController
    {
        private readonly IStudiesService _service;
        public StudiesController(IStudiesService service)
        {
            _service = service;
        }

        // GET: Studies
        public async Task<ActionResult> Index() { await BindStudiesData(); return View(); }

        [HttpPost]
        public async Task<JsonResult> Index(DataTableAjaxPostModel model) => Json(await _service.GetFilteringList(model));

        public async Task<ActionResult> Add()
        {
            await BindStudiesData();
            return View("AddUpdate", new ManageStudiesModel());
        }

        [HttpPost]
        public async Task<ActionResult> Add(ManageStudiesModel model)
        {
            if (ModelState.IsValid)
            {
                model.UId = User.Identity.GetUserId();
                ResponseModel mResult = await _service.AddUpdate(model);
                OnBindToastMessage(mResult);
                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToAction("Index");
            }
            await BindStudiesData();
            return View("AddUpdate", model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            ResponseModel<ManageStudiesModel> mResult = await _service.GetDetailsForEdit(id);
            if (mResult != null && mResult.Result != null && mResult.Status == ResponseStatus.Success)
            {
                await BindStudiesData();
                return View("AddUpdate", mResult.Result);
            }
            OnBindToastMessage(mResult);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(ManageStudiesModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseModel mResult = await _service.AddUpdate(model);
                OnBindToastMessage(mResult);
                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToAction("Index");
            }
            return View("AddUpdate", model);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id) => Json(await _service.DeleteAsync(new IBaseIdModel() { Id = id }));

        public async Task<PartialViewResult> AddNewStudyDetails()
        {
            await BindStudiesData();
            return PartialView("_StudyDetails", new StudyDetailsManageModel() { StudyNo = "PSN19-" + Utilities.GetRandomAlphaNumeric(3) });
        }

    }
}

Pharmidex.Admin/Views/Studies/AddUpdate.cshtml
@model ManageStudiesModel
@{
    ViewBag.Title = ViewBag.Action + " Studies";
    string _action = ViewBag.Action;
}
@section Styles{
    @Styles.Render("~/css/addupdate")
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
}
<div class="row">
    <div class="col-12">
        <div class="card box-shadow-0 border-blue border-bottom-3">
            <div class="card-header card-head-inverse">
                <h4 class="card-title text-black-50">
                    @{
                        if (_action == "Add")
                        {
                            <i class="fa fa-fw fa-plus"></i>
                        }
                        else
                        {
                            <i class="fa fa-fw fa-edit"></i>
                        }
                    }@_action Studies
                </h4>
            </div>
            <div class="card-content collapse show pl-2">
                @using (Html.BeginForm(_action, "Studies", FormMethod.Post, new { Id = "frmSubmit" }))
                {
                    @Html.AntiForgeryToken()
                    if (Model != null)
                    {
                        @Html.HiddenFor(x => x.Id)
                    }
                    <div class="card-body">
                        <div class="form-body">
                            <div class="form-group row">
                                <div class="col-md-12 col-lg-12">
                                    <div class="form-group row">
                                        <div class="col-md-3">
                                            <label>Select Customer<span class="red">*</span></label>
                                            @Html.DropDownListFor(x => x.CustomerId, new SelectList(ViewData["CustomersList"] as IEnumerable<DropdownListItemModel>, "Value", "Text"), new
                               {
                                   @class = "form-control select2"
                               })
                                        </div>
                                        <div class="col-md-3">
                                            <label>Proposal Number <span class="red">*</span></label>
                                            @Html.TextBoxFor(x => x.ProposalNo, new { @class = "form-control", @placeholder = "Proposal Number" })
                                            @Html.ValidationMessageFor(x => x.ProposalNo)
                                        </div>
                                        <div class="col-md-3">
                                            <label>Proposal Date <span class="red">*</span></label>
                                            @Html.TextBoxFor(x => x.ProposalDate, new { @class = "form-control datepicker", @placeholder = "Proposal Date" })
                                            @Html.ValidationMessageFor(x => x.ProposalDate)
                                        </div>
                                        <div class="col-md-3">
                                            <label></label>
                                            <a href="javascript:;" id="addStudentDetails" class="btn btn-blue mr-1">
                                                <i class="fa fa-plus fa-fw"></i>&nbsp;Add new study details
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-md-12 p-0" id="div_study_details">
                            @if (Model.StudyDetails != null && Model.StudyDetails.Any())
                            {
                                foreach (var item in Model.StudyDetails)
                                {
                                    @Html.Partial("_StudyDetails", item)
                                }
                            }
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="@Url.Action("Index", "ServiceProvider")" class="btn btn-grey">
                            <i class="fa fa-arrow-left fa-fw"></i>&nbsp;Go to List
                        </a>
                        <button type="submit" class="btn btn-blue pull-right frmSubmit mb-1">
                            <i class="fa fa-save fa-fw"></i><text>&nbsp; Submit</text>
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    @Scripts.Render("~/jquery/addupdate")
    <script type="text/javascript">
        ActiveMenu("Studies");
        $(function () {
            $('#ProposalDate').daterangepicker({
                autoUpdateInput: true,
                singleDatePicker: true,
                showDropdowns: true,
                startDate: moment().add(0, 'day'),
                locale: {
                    cancelLabel: 'Cancel',
                    format: 'DD-MMMM-YYYY'
                }
            });
            $("#CustomerId").select2({
                placeholder: "Select Customer",
                allowClear: true,
                multiple: false,
            });
        });

        $("#addStudentDetails").on("click",function () {
                StartBlockPage();
            var Url = '@Url.Action("AddNewStudyDetails")';
                $.get(Url, function (template) {
                    $("#div_study_details").append(template);
                }).done(function (responce) {
                    CloseBlockPage();
                });
          });

        function removeStudyDetails(element) {
            var dId = $(element).data("id");
            var removecp = $(element).closest('.removeDetails')[0];
            console.log(dId)
            if (dId <= 0) {
                Swal.fire({
                    title: "Are you sure do you want to delete this details?",
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: "No, cancel!",
                    showClass: {
                        popup: 'animate__animated animate__fadeInDown'
                    },
                    hideClass: {
                        popup: 'animate__animated animate__fadeOutUp'
                    }
                }).then((result) => {
                    if (result.isConfirmed) {
                        removecp.remove()
                        Swal.fire("Success!", "Details removed!", "success");
                    }
                    else {
                        control.children('i').addClass('fa-trash').removeClass('fa-spinner spinner');
                    }
                })
            }
            else {
                removecp.remove()
            }
        }
    </script>
}

Pharmidex.Admin/Views/Studies/Index.cshtml
@{
    ViewBag.Title = "Studies";
}
@Styles.Render("~/css/viewgrid")
@Styles.Render("~/css/select2")
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<div class="row">
    <div class="col-12">
        <div class="card box-shadow-0 border-blue border-bottom-3">
            <div class="card-header card-head-inverse bg-blue">
                <h4 class="card-title text-white">Filter options for studies!</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3 white"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li class="hidden-sm-down">
                            <a data-action="collapse"><i class="fa fa-minus text-white font-size-large"></i></a>
                        </li>
                        <li class="hidden-sm-down">
                            <a data-action="expand"><i class="fa fa-expand text-white font-size-large"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card-content collapse show p-2">
                <div class="card-block">
                    <div class="col-12">
                        <div class="form-group row">
                            <div class="col-md-3">
                                @Html.DropDownList("DepartmentId", new SelectList(ViewData["DepartmentList"] as IEnumerable<DropdownListItemModel>, "Value", "Text"), new
                           {
                               @class = "form-control select2"
                           })
                            </div>
                            <div class="col-md-2">
                                @Html.DropDownList("DerecorId", new SelectList(ViewData["DirectorList"] as IEnumerable<DropdownListItemModel>, "Value", "Text"), new
                           {
                               @class = "form-control select2"
                           })
                            </div>
                            <div class="col-md-2">
                                @Html.DropDownList("StudyTypeId", new SelectList(ViewData["StudyTypeList"] as IEnumerable<DropdownListItemModel>, "Value", "Text"), new
                           {
                               @class = "form-control select2"
                           })
                            </div>
                            <divl class="col-md-3">

                                @Html.TextBox("DateRange", "", new { @class = "form-control daterange" })
                            </divl>
                            <div class="col-md-2">
                                <a href="@Url.Action("Add")" class="btn btn-blue mr-1">
                                    <i class="fa fa-search"></i>&nbsp;Search
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card box-shadow-0 border-blue border-bottom-3">
            <div class="card-header card-head-inverse bg-white">
                <h4 class="card-title text-black-50">
                    <i class="fa fa-fw fa-cogs"></i>&nbsp;Manage Studies
                </h4>
                <a class="heading-elements-toggle">
                    <i class="fa fa-ellipsis-v fa-fw font-medium-3"></i>
                </a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a href="@Url.Action("Add")" class="btn btn-blue mr-1">
                                <i class="fa fa-plus fa-fw"></i>&nbsp;Add New
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card-content collapse show">
                <div class="card-body">
                    <table class="table table-striped table-bordered datatable" id="datatable" style="width:100% !important"></table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    @Scripts.Render("~/jquery/viewgrid")
    @Scripts.Render("~/jquery/select2")
    <script type="text/javascript">
        ActiveMenu("Studies");
        $(document).ready(function () {
            $(".select2").select2({
                allowClear: true,
            });
            $('.daterange').daterangepicker({
                autoUpdateInput: true,
                singleDatePicker: false,
                showDropdowns: true,
                locale: {
                    cancelLabel: 'Cancel',
                    format: 'DD/MMMM/YYYY'
                }
            });
            $('#datatable').DataTable({
                proccessing: true,
                serverSide: true,
                responsive: true,
                fixedHeader: {
                    header: true,
                    headerOffset: $('.header-navbar').outerHeight()
                },
                language: {
                    search: "",
                    searchPlaceholder: "Search..."
                },
                ajax: {
                    url: "@Url.Action("Index", "Studies")",
                    type: 'POST'
                },
                order: [[2, "@GlobalConfig.asc"]],
                columns: [
                    { data: "CustomerName", title: "Customer Name"},
                    { data: "ProposalNo", title: "Proposal No"},
                    {
                        data: "ProposalDate", title: "Proposal Date",
                        mRender: function (x) {
                            return moment(x).utc(x).local().format("DD/MM/YYYY")
                        }
                    },
                    { data: "Count", title: "Studies Count" },
                    {
                        data: null,
                        title: "Action",
                        sortable: false,
                        searchable: false,
                        orderable: false,
                        mRender: function (x) {
                            return BindActionButtons(x);
                        }
                    }
                ]
            });
        });

    const BindActionButtons = (data) => {
        var strButtons = '';
        //Edit button
        strButtons += '<a href="@Url.Action("Edit", "Studies")/' + data.Id + '" class="btn btn-sm btn-blue m-1">';
        strButtons += '<i class="fa fa-edit"></i> Edit';
        strButtons += '</a>';

        strButtons += '<a href="javascript:;" onclick="DeleteRecord($(this))" data-id="' + data.Id + '" class="btn btn-sm btn-primary btn-red m-1" ';
        strButtons += 'data-url="@Url.Action("Delete", "ServiceProvider")"" >';
        strButtons += '<i class="fa fa-trash"></i> <span>Delete</span>';
        strButtons += '</a>';
        return strButtons;
    };
    </script>
}